services:
  tests:
    container_name: utopia-video-test-1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        TESTING: "true"
        PHP_VERSION: ${PHP_VERSION:-8.2}
    volumes:
      - ./src:/usr/src/code/src
      - ./tests:/usr/src/code/tests
      - ./phpunit.xml:/usr/src/code/phpunit.xml
      - ./phpstan.neon:/usr/src/code/phpstan.neon
      - ./pint.json:/usr/src/code/pint.json
