name: "Static analysis"

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Run PHPStan
        run: |
          docker run --rm -v $PWD:/app composer:2 sh -c \
          "composer install --profile && composer check"
